### PR TITLE
Proofing-Tools

### PR DESCRIPTION
**Pull request by ravager-dk**
Added paramter for installing Proofing tools

### CODE REVIEW

**Comment by ravager-dk** [comment]
Forgot to squish commits. My appologies

**Comment by FreeMinded** [comment]
@ravager-dk tThanks a lot for this MR! What is the reason you add a dedicated language list for the ProofingTools? Could you use the already existing language list in /tools/lists/languagesList.txt?

**Comment by ravager-dk** [comment]
> @ravager-dk tThanks a lot for this MR! What is the reason you add a dedicated language list for the ProofingTools? Could you use the already existing language list in /tools/lists/languagesList.txt?

You likely could. Although I do believe there are some languages that are only available as proofing tools - I've however been unable to find the definitive list. Currently the files are the same. If nothing else the separation into two files makes it possible.

**Comment by ravager-dk** [comment]
I see I made some mistakes in the code. Will close the PR and make a new one.

**Pull request closed without merging**
